# How to look up price Data for finnhub Data

In [1]:
import os
import pandas as pd
from aiq_strategy_robot.data.data_accessor import DAL

In [2]:
## load wrapper
from aiq_strategy_robot.data.FINNHUB import (
    load_finnhub_equity_prices,
    load_finnhub_dividends,
    load_finnhub_stock_splits,
    load_finnhub_equity_data
)

In [3]:
sdh = DAL()

## stock prices

In [4]:
load_finnhub_equity_prices(
    sdh,
    symbols='8035.T', 
    freq='60', 
    start_datetime='2023-12-29', 
    end_datetime='2024-02-01'
).retrieve()

8035.T: loading...: 100%|██████████| 1/1 [00:00<00:00,  3.05it/s]

                            close   high    low   open  volume exchange_code
TICKER DATETIME
8035   2024-01-04 01:00:00  24005  24105  23975  24025  745400            JT
       2024-01-04 02:00:00  24000  24020  23970  24010  222600            JT
       2024-01-04 03:00:00  24070  24075  23985  24005  242200            JT
       2024-01-04 04:00:00  24040  24080  24025  24065  341100            JT
       2024-01-04 05:00:00  24015  24055  24005  24045  469200            JT
...                           ...    ...    ...    ...     ...           ...
       2024-01-31 02:00:00  27520  27590  27510  27535  123500            JT
       2024-01-31 03:00:00  27615  27635  27535  27580  212300            JT
       2024-01-31 04:00:00  27685  27690  27595  27620  281500            JT
       2024-01-31 05:00:00  27860  27860  27680  27680  359400            JT
       2024-02-01 00:00:00  27555  27555  27480  27480  166700            JT

[114 rows x 6 columns]

In [5]:
load_finnhub_equity_prices(
    sdh,
    symbols='AMZN', 
    freq='D', 
    start_datetime='2023-12-29', 
    end_datetime='2024-02-01'
).retrieve()

AMZN: loading...: 100%|██████████| 1/1 [00:00<00:00,  3.65it/s]

                    close     high       low    open    volume exchange_code
TICKER DATETIME
AMZN   2023-12-29  151.94  153.890  151.0300  153.10  39823204            US
       2024-01-02  149.93  152.380  148.3900  151.54  47339424            US
       2024-01-03  148.47  151.050  148.3300  149.20  49425495            US
       2024-01-04  144.57  147.380  144.0500  145.59  56039807            US
       2024-01-05  145.24  146.590  144.5300  144.69  45153147            US
       2024-01-08  149.10  149.400  146.1500  146.74  46757053            US
       2024-01-09  151.37  151.710  148.2100  148.33  43812567            US
       2024-01-10  153.73  154.420  151.8810  152.06  44421830            US
       2024-01-11  155.18  157.170  153.1200  155.04  49072691            US
       2024-01-12  154.62  156.200  154.0100  155.39  40484155            US
       2024-01-16  153.16  154.990  152.1500  153.53  41384636            US
       2024-01-17  151.71  152.150  149.9100  151.49  34953363            US
       2024-01-18  153.50  153.775  151.8200  152.77  37850245            US
       2024-01-19  155.34  155.760  152.7400  153.83  51651628            US
       2024-01-22  154.78  157.050  153.9000  156.89  43687468            US
       2024-01-23  156.02  156.210  153.9300  154.85  37986039            US
       2024-01-24  156.87  158.510  156.4800  157.80  48547315            US
       2024-01-25  157.75  158.505  154.5501  156.95  43638592            US
       2024-01-26  159.12  160.720  157.9100  158.42  51047353            US
       2024-01-29  161.26  161.290  158.9000  159.34  45270385            US
       2024-01-30  159.00  161.730  158.4900  160.70  45207430            US
       2024-01-31  155.20  159.010  154.8100  157.00  50284371            US
       2024-02-01  159.28  159.760  155.6200  155.87  76542419            US

## dividends

In [6]:
load_finnhub_dividends(
    sdh,
    symbols='8035.T',
    start_datetime='2015-09-30', 
    end_datetime='2023-12-31'
).retrieve()

8035.T: loading...: 100%|██████████| 1/1 [00:00<00:00,  2.82it/s]

                   adjustedAmount      amount currency declarationDate  \
TICKER DATETIME
8035   2016-03-29       37.333300  112.000000      JPY      2016-04-26
       2016-09-28       42.666700  128.000000      JPY      2016-10-28
       2017-03-29       74.666700  224.000000      JPY      2017-04-28
       2017-09-27       92.333300  277.000000      JPY      2017-10-31
       2018-03-28      115.666700  347.000000      JPY      2018-04-25
       2018-09-26      137.666700  413.000000      JPY      2018-10-31
       2019-03-27      115.000000  345.000000      JPY      2019-04-26
       2019-09-27       82.000000  246.000000      JPY      2019-10-31
       2020-03-30      114.000000  342.000000      JPY      2020-04-30
       2020-09-29      120.000000  360.000000      JPY      2020-10-29
       2021-03-30      140.333300  421.000000      JPY      2021-04-30
       2021-09-29      214.333300  643.000000      JPY      2021-11-12
       2022-03-30      253.333300  760.000000      JPY      2022-05-12
       2022-09-29      285.666700  857.000000      JPY      2022-11-10
       2023-03-30      218.000000  218.000000      JPY      2023-05-11
       2023-03-30       66.666664   66.666664      JPY      2023-05-11
       2023-09-28      148.000000  148.000000      JPY      2023-11-10

                   franking freq     payDate  recordDate exchange_code
TICKER DATETIME
8035   2016-03-29         0    3  2016-05-27  2016-03-31            JT
       2016-09-28         0    3  2016-11-28  2016-09-30            JT
       2017-03-29         0    3  2017-05-30  2017-03-31            JT
       2017-09-27         0    3  2017-11-27  2017-09-30            JT
       2018-03-28         0    3  2018-05-29  2018-03-31            JT
       2018-09-26         0    3  2018-11-26  2018-09-30            JT
       2019-03-27         0    3  2019-05-28  2019-03-31            JT
       2019-09-27         0    3  2019-11-25  2019-09-30            JT
       2020-03-30         0    3  2020-06-02  2020-03-31            JT
       2020-09-29         0    3  2020-11-27  2020-09-30            JT
       2021-03-30         0    3  2021-05-28  2021-03-31            JT
       2021-09-29         0    3  2021-12-09  2021-09-30            JT
       2022-03-30         0    3  2022-05-31  2022-03-31            JT
       2022-09-29         0    3  2022-12-07  2022-09-30            JT
       2023-03-30         0    3  2023-05-31  2023-03-31            JT
       2023-03-30         0    4  2023-05-31  2023-03-31            JT
       2023-09-28         0    3  2023-12-07  2023-09-30            JT

In [7]:
load_finnhub_dividends(
    sdh,
    symbols='AMZN',
    start_datetime='2015-09-30', 
    end_datetime='2023-12-31'
).retrieve()

AMZN: loading...: 100%|██████████| 1/1 [00:00<00:00,  3.43it/s]

Empty DataFrame
Columns: []
Index: []

## stock splits

In [8]:
load_finnhub_stock_splits(
    sdh,
    symbols='8035.T',
    start_datetime='2015-09-30', 
    end_datetime='2023-12-31'
).retrieve()

8035.T: loading...: 100%|██████████| 1/1 [00:00<00:00,  3.04it/s]

                   split_ratio exchange_code
TICKER DATETIME
8035   2023-03-30     0.333333            JT

In [9]:
load_finnhub_stock_splits(
    sdh,
    symbols='GOOG',
    start_datetime='2015-09-30', 
    end_datetime='2023-12-31'
).retrieve()

GOOG: loading...: 100%|██████████| 1/1 [00:00<00:00,  2.83it/s]

                   split_ratio exchange_code
TICKER DATETIME
GOOG   2015-10-05         1.00            US
       2022-07-18         0.05            US

## Load Market Data, Dividends, and Split ratios in one call

In [10]:
load_finnhub_equity_data(
    sdh,
    symbols=['AMZN', '8035.T'],
    freq='D',
    # split_adjust=False, 👈 Apply stock split adjustment. Default = TRUE (applied)
    # div_adjust=False,   👈 Apply dividend adjustment. Default = TRUE (applied)
    start_datetime='2015-09-30', 
    end_datetime='2024-01-01'
).retrieve()

8035.T: loading...: 100%|██████████| 2/2 [00:03<00:00,  1.68s/it]

                          close          high           low          open  \
TICKER DATETIME
AMZN   2015-09-30     25.594500     25.640000     25.083620     25.272000
       2015-10-01     26.036000     26.040000     25.300000     25.550000
       2015-10-02     26.627000     26.630000     25.405000     25.649500
       2015-10-05     27.184000     27.295500     26.800000     26.849500
       2015-10-06     26.874000     27.575000     26.666500     27.275000
...                         ...           ...           ...           ...
8035   2023-12-25  24613.978441  24722.171753  24461.524229  24692.664486
       2023-12-26  24884.461721  24884.461721  24436.934840  24613.978441
       2023-12-27  25199.205901  25553.293103  25076.258955  25233.631045
       2023-12-28  25046.751689  25199.205901  24963.147766  25199.205901
       2023-12-29  24840.200821  25002.490788  24717.253875  24884.461721

                     volume exchange_code  div_ratio  split_ratio
TICKER DATETIME
AMZN   2015-09-30  80093620            US   1.000000         0.05
       2015-10-01  75369660            US   1.000000         0.05
       2015-10-02  91955900            US   1.000000         0.05
       2015-10-05  67827180            US   1.000000         0.05
       2015-10-06  90950380            US   1.000000         0.05
...                     ...           ...        ...          ...
8035   2023-12-25   1427100            JT   0.983576         1.00
       2023-12-26   1585300            JT   0.983576         1.00
       2023-12-27   2783200            JT   0.983576         1.00
       2023-12-28   1612500            JT   0.983576         1.00
       2023-12-29   2257900            JT   0.983576         1.00

[4094 rows x 8 columns]

## Appendix

> Handler.load()

Can also be obtained directly from the handler without using the wrapper.<br>
In this case, `data_source` and `data_type` must be specified.

In [11]:
sdh.load(
    'finnhub', 
    data_type='equity_prices',
    symbols='8035.T', 
    freq='60', 
    start_datetime='2023-12-29', 
    end_datetime='2024-02-01'
).retrieve()

8035.T: loading...: 100%|██████████| 1/1 [00:00<00:00,  2.92it/s]

                            close   high    low   open  volume exchange_code
TICKER DATETIME
8035   2024-01-04 01:00:00  24005  24105  23975  24025  745400            JT
       2024-01-04 02:00:00  24000  24020  23970  24010  222600            JT
       2024-01-04 03:00:00  24070  24075  23985  24005  242200            JT
       2024-01-04 04:00:00  24040  24080  24025  24065  341100            JT
       2024-01-04 05:00:00  24015  24055  24005  24045  469200            JT
...                           ...    ...    ...    ...     ...           ...
       2024-01-31 02:00:00  27520  27590  27510  27535  123500            JT
       2024-01-31 03:00:00  27615  27635  27535  27580  212300            JT
       2024-01-31 04:00:00  27685  27690  27595  27620  281500            JT
       2024-01-31 05:00:00  27860  27860  27680  27680  359400            JT
       2024-02-01 00:00:00  27555  27555  27480  27480  166700            JT

[114 rows x 6 columns]

In [12]:
sdh.load(
    'finnhub', 
    data_type='dividends',
    symbols='8035.T',
    start_datetime='2015-09-30', 
    end_datetime='2023-12-31'
).retrieve()

8035.T: loading...: 100%|██████████| 1/1 [00:00<00:00,  2.63it/s]

                   adjustedAmount      amount currency declarationDate  \
TICKER DATETIME
8035   2016-03-29       37.333300  112.000000      JPY      2016-04-26
       2016-09-28       42.666700  128.000000      JPY      2016-10-28
       2017-03-29       74.666700  224.000000      JPY      2017-04-28
       2017-09-27       92.333300  277.000000      JPY      2017-10-31
       2018-03-28      115.666700  347.000000      JPY      2018-04-25
       2018-09-26      137.666700  413.000000      JPY      2018-10-31
       2019-03-27      115.000000  345.000000      JPY      2019-04-26
       2019-09-27       82.000000  246.000000      JPY      2019-10-31
       2020-03-30      114.000000  342.000000      JPY      2020-04-30
       2020-09-29      120.000000  360.000000      JPY      2020-10-29
       2021-03-30      140.333300  421.000000      JPY      2021-04-30
       2021-09-29      214.333300  643.000000      JPY      2021-11-12
       2022-03-30      253.333300  760.000000      JPY      2022-05-12
       2022-09-29      285.666700  857.000000      JPY      2022-11-10
       2023-03-30      218.000000  218.000000      JPY      2023-05-11
       2023-03-30       66.666664   66.666664      JPY      2023-05-11
       2023-09-28      148.000000  148.000000      JPY      2023-11-10

                   franking freq     payDate  recordDate exchange_code
TICKER DATETIME
8035   2016-03-29         0    3  2016-05-27  2016-03-31            JT
       2016-09-28         0    3  2016-11-28  2016-09-30            JT
       2017-03-29         0    3  2017-05-30  2017-03-31            JT
       2017-09-27         0    3  2017-11-27  2017-09-30            JT
       2018-03-28         0    3  2018-05-29  2018-03-31            JT
       2018-09-26         0    3  2018-11-26  2018-09-30            JT
       2019-03-27         0    3  2019-05-28  2019-03-31            JT
       2019-09-27         0    3  2019-11-25  2019-09-30            JT
       2020-03-30         0    3  2020-06-02  2020-03-31            JT
       2020-09-29         0    3  2020-11-27  2020-09-30            JT
       2021-03-30         0    3  2021-05-28  2021-03-31            JT
       2021-09-29         0    3  2021-12-09  2021-09-30            JT
       2022-03-30         0    3  2022-05-31  2022-03-31            JT
       2022-09-29         0    3  2022-12-07  2022-09-30            JT
       2023-03-30         0    3  2023-05-31  2023-03-31            JT
       2023-03-30         0    4  2023-05-31  2023-03-31            JT
       2023-09-28         0    3  2023-12-07  2023-09-30            JT

In [13]:
sdh.load(
    'finnhub', 
    data_type='stock_splits',
    symbols='8035.T',
    start_datetime='2015-09-30', 
    end_datetime='2023-12-31'
).retrieve()

8035.T: loading...: 100%|██████████| 1/1 [00:00<00:00,  2.62it/s]

                   split_ratio exchange_code
TICKER DATETIME
8035   2023-03-30     0.333333            JT

In [14]:
sdh.load(
    'finnhub', 
    data_type='equity_data',
    symbols=['AMZN', '8035.T'],
    freq='D',
    start_datetime='2015-09-30', 
    end_datetime='2024-01-01'
).retrieve()

8035.T: loading...: 100%|██████████| 2/2 [00:03<00:00,  1.83s/it]

                          close          high           low          open  \
TICKER DATETIME
AMZN   2015-09-30     25.594500     25.640000     25.083620     25.272000
       2015-10-01     26.036000     26.040000     25.300000     25.550000
       2015-10-02     26.627000     26.630000     25.405000     25.649500
       2015-10-05     27.184000     27.295500     26.800000     26.849500
       2015-10-06     26.874000     27.575000     26.666500     27.275000
...                         ...           ...           ...           ...
8035   2023-12-25  24613.978441  24722.171753  24461.524229  24692.664486
       2023-12-26  24884.461721  24884.461721  24436.934840  24613.978441
       2023-12-27  25199.205901  25553.293103  25076.258955  25233.631045
       2023-12-28  25046.751689  25199.205901  24963.147766  25199.205901
       2023-12-29  24840.200821  25002.490788  24717.253875  24884.461721

                     volume exchange_code  div_ratio  split_ratio
TICKER DATETIME
AMZN   2015-09-30  80093620            US   1.000000         0.05
       2015-10-01  75369660            US   1.000000         0.05
       2015-10-02  91955900            US   1.000000         0.05
       2015-10-05  67827180            US   1.000000         0.05
       2015-10-06  90950380            US   1.000000         0.05
...                     ...           ...        ...          ...
8035   2023-12-25   1427100            JT   0.983576         1.00
       2023-12-26   1585300            JT   0.983576         1.00
       2023-12-27   2783200            JT   0.983576         1.00
       2023-12-28   1612500            JT   0.983576         1.00
       2023-12-29   2257900            JT   0.983576         1.00

[4094 rows x 8 columns]